(custom-set-variables
 '(abbrev-file-name "~/.emacs-abbrevs" t)
 '(align-c++-modes (quote (c++-mode c-mode java-mode javascript-generic-mode)))
 '(align-open-comment-modes (quote (vhdl-mode emacs-lisp-mode lisp-interaction-mode lisp-mode scheme-mode c++-mode c-mode java-mode perl-mode cperl-mode python-mode makefile-mode javascript-generic-mode)))
 '(archive-zip-use-pkzip nil)
 '(browse-url-browser-function (quote browse-url-w3))
 '(buffers-menu-max-size nil)
 '(buffers-menu-submenus-for-groups-p t)
 '(case-fold-search t)
 '(column-number-mode t)
 '(complex-buffers-menu-p t)
 '(confirm-kill-emacs (quote y-or-n-p))
 '(display-time-24hr-format t)
 '(display-time-mail-face (quote mode-line))
 '(display-time-mail-file (quote none))
 '(display-time-string-forms (quote ((format-time-string (or display-time-format (if display-time-24hr-format "%H:%M" "%-I:%M%p")) now))) t)
 '(generic-define-mswindows-modes t)
 '(generic-define-unix-modes t)
 '(grep-command "grep -r -n -P ")
 '(init-face-from-resources nil)
 '(line-number-mode t)
 '(mouse-yank-at-point t)
 '(mwheel-follow-mouse t)
 '(mwheel-scroll-amount (quote (6 . 1)))
 '(outline-plain-bullets-string "·§-+.:,;¶¤»×°")
 '(outline-regexp "[*§¶]+\\|[ 	]+[-+¤°»]+" t)
 '(ps-printer-name "~/emacs-out.ps")
 '(require-final-newline nil)
 '(revert-without-query (quote (".*")))
 '(save-abbrevs (quote silently))
 '(transient-mark-mode 1)
 '(type-break-good-rest-interval 60)
 '(type-break-interval 600)
 '(type-break-mode-line-message-mode nil)
 '(type-break-time-warning-intervals (quote (60 30)))
 '(visual-basic-mode-indent 2 t)
 '(woman-cache-filename "~/.emacs.d/.wmncache.el")
 '(woman-cache-level 1)
 '(woman-use-own-frame nil)
)

(custom-set-faces
 )

(setq minibuffer-max-depth nil)
